package l1j.server.server; // 변경  by feel.  160913

public class Opcodes {

	public Opcodes() {
	}
	/**old kor*/
//	public static final int C_PLATE = 0x01;	// 게시판 클릭
//	public static final int C_LOGIN_TEST = 0x04;	// 찾음[본섭]  (현재 미사용 by feel)
//	public static final int C_CHANGE_ACCOUNTINFO = 0x05;	// CALL버튼 .감시  (현재 미사용 by feel)
//	public static final int C_BLINK = 0x08;	// 찾음[본섭]  (현재 미사용 by feel)
//	public static final int C_BUYABLE_SPELL = 0x0B;	// 스킬 구입 리스트
//	public static final int C_HYPERTEXT_INPUT_RESULT = 0x0C;	// 수량성 아이템 제작 갯수
//	public static final int C_ADD_BUDDY = 0x0D;	// 친구추가
//	public static final int C_WITHDRAW = 0x0E;	// 공금 출금[자금을 인출한다]
//	public static final int C_TELL = 0x11;	// 찾음[본섭]
//	public static final int C_ACCEPT_XCHG = 0x12;	// 교환 OK
//	public static final int C_READ_NOTICE = 0x16;	// 로그인 후 패킷
//	public static final int C_HACTION = 0x17;	// Npc 대화 액션 부분
//	public static final int C_EXCHANGEABLE_SPELL = 0x18;	// 호런 마법 리스트
//	public static final int C_USE_SPELL = 0x19;	// 스킬 사용 부분
//	public static final int C_ATTACK = 0x1A;	// 일반공격 부분
//	public static final int C_UPLOAD_EMBLEM = 0x1C;	// 문장데이타를 서버에 요청함
//	public static final int C_MERCENARYSELECT = 0x99;	// 찾음[본섭]  (현재 미사용 by feel)
//	public static final int C_USE_ITEM = 0x21;	// 아이템 사용 부분
//	public static final int C_LEAVE_PLEDGE = 0x22;	// 혈맹 탈퇴
//	public static final int C_RANK_CONTROL = 0x24;	// [계급]
//	public static final int C_BOOKMARK = 0x28;	// [기억 OO]
//	public static final int C_MOVE = 0x29;	// 이동요청 부분
//	public static final int C_SAY = 0x2A;	// 찾음[본섭]
//	public static final int C_WHO_PLEDGE = 0x2B;	// [혈맹]
//	public static final int C_MERCENARYARRANGE = 0x2D;	// 찾음[본섭]  (현재 미사용 by feel)
//	public static final int C_MONITOR_CONTROL = 0x2E;	// 찾음[본섭]  (현재 미사용 by feel)
//	public static final int C_SLAVE_CONTROL = 0x30;	// 펫 공격 목표 지정
//	public static final int C_SAVEIO = 0x31;	// 캐릭인벤슬롯정보
//	public static final int C_WANTED = 0x32;	// 찾음[본섭]  (현재 미사용 by feel)
//	public static final int C_EXCLUDE = 0x33;	// [/차단]
//	public static final int C_DROP = 0x34;	// 아이템 떨구기
//	public static final int C_ALIVE = 0x35;	// 1분마다 한번씩 옴
//	public static final int C_BUILDER_CONTROL = 0x36;	// 찾음[본섭]  (현재 미사용 by feel)
//	public static final int C_SELECT_TIME = 0x3A;	// 찾음[본섭]  (현재 미사용 by feel)
//	public static final int C_INCLUDE = 0x3B;	// [포함]  (현재 미사용 by feel)
//	public static final int C_PERSONAL_SHOP = 0x3C;	// [상점 -> OK]
//	public static final int C_DELETE_CHARACTER = 0x3D;	// 케릭터 삭제
//	public static final int C_SHUTDOWN = 0x3F;	// 혈맹창 공지, 메모
//	public static final int C_WHO = 0x42;	// [누구]
//	public static final int C_VERSION = 0x46;	// v 클라 서버 버전 (현재 미사용 by feel)
//	public static final int C_WHO_PARTY = 0x47;	// 찾음[본섭]
//	public static final int C_LOGIN_RESULT = 0x4C;	// 찾음[본섭]  (현재 미사용 by feel)
//	public static final int C_RETURN_SUMMON = 0x4D;	// 텔레포트 사용
//	public static final int C_QUERY_PERSONAL_SHOP = 0x4E;	// 개인상점 buy, sell
//	public static final int C_EXTENDED_PROTOBUF = 0x51;	// 종합 패킷
//	public static final int C_BAN = 0x52;	// 찾음[본섭] (현재 미사용 by feel)
//	public static final int C_CANCEL_XCHG = 0x53;	// 교환 취소
//	public static final int C_NPC_ITEM_CONTROL = 0x54;	// 펫 인벤토리 아이템 사용
//	public static final int C_LEAVE_PARTY = 0x55;	// 파티 탈퇴
//	public static final int C_GOTO_MAP = 0x59;	// 찾음[본섭]
//	public static final int C_ADD_XCHG = 0x5B;	// 교환창에 아이템 추가
//	public static final int C_WAREHOUSE_CONTROL = 0x61;	// 창고 비번.
//	public static final int C_MARRIAGE = 0x62;	// [청혼]
//	public static final int C_CHANNEL = 0x63;	// 불량 유저 신고(신고)
//	public static final int C_CONTROL_WEATHER = 0x64;	// 찾음[본섭]  (현재 미사용 by feel)
//	public static final int C_GET = 0x65;	// 아이템 줍기.
//	public static final int C_CREATE_CUSTOM_CHARACTER = 0x67;	// 케릭 생성
//	public static final int C_TELEPORT = 0x69;	// 찾음[본섭] (현재 미사용 by feel)
//	public static final int C_KICK = 0x6A;	// 찾음[본섭] (현재 미사용 by feel)
//	public static final int C_ADDR = 0x6B;	// 찾음[본섭] (현재 미사용 by feel)
//	public static final int C_DEAD_RESTART = 0x6D;	// 겜중에 죽어서 리셋 눌럿을때
//	public static final int C_QUERY_CASTLE_SECURITY = 0x6E;	// 성내 치안관리
//	public static final int C_GIVE = 0x72;	// 강제로 아이템 주기
//	public static final int C_CHAT = 0x73;	// 매크로 체팅 by feel
//	public static final int C_MERCENARYNAME = 0x74;	// 찾음[본섭]  (현재 미사용 by feel)
//	public static final int C_FIX = 0x78;	// 무기수리, 펫인출
//	public static final int C_QUERY_BUDDY = 0x7A;	// 친구리스트
//	public static final int C_FAR_ATTACK = 0x7B;	// 활공격 부분
//	public static final int C_CHANGE_PASSWORD = 0x7C;	// 찾음[본섭] (사용안함_by feel )
//	public static final int C_TELEPORT_USER = 0x7D;	// 찾음[본섭] (현재 미사용 by feel)
//	public static final int C_CHANGE_DIRECTION = 0x80;	//
//	public static final int C_NEW_ACCOUNT = 0x82;	// 찾음[본섭] (사용안함_by feel )
//	public static final int C_SELECTABLE_TIME = 0x85;	// 찾음[본섭]  (현재 미사용 by feel)
//	public static final int C_WISH = 0x86;	// 찾음[본섭] (현재 미사용 by feel)
//	public static final int C_EXTENDED = 0x89;	// 아덴상점 아이콘 클릭, 부가 아이템, 혈맹창
//	public static final int C_READ_NEWS = 0x8B;	// 공지사항 확인 눌럿을때
//	public static final int C_OPEN = 0x8E;	// 문짝 클릭 부분.
//	public static final int C_DUEL = 0x90;	// [결투]
//	public static final int C_ASK_XCHG = 0x91;	// [교환]
//	public static final int C_REGISTER_QUIZ = 0x93;	// 찾음[본섭] (현재 미사용 by feel)
//	public static final int C_FIXABLE_ITEM = 0x96;	// 무기수리리스트
//	public static final int C_CHECK_PK = 0x97;	// [checkpk]
//	public static final int C_SERVER_SELECT = 0x99;	// 찾음[본섭] (현재 미사용 by feel)
//	public static final int C_EXTENDED_HYBRID = 0x9A;	// 찾음[본섭]  (현재 미사용 by feel)
//	public static final int C_TITLE = 0x9B;	// 호칭 명령어
//	public static final int C_ARCHERARRANGE = 0x9C;	// 찾음[본섭]  (현재 미사용 by feel)
//	public static final int C_DELETE_BOOKMARK = 0x9D;	// [기억 후 기억목록클릭 delete]
//	public static final int C_QUIT = 0xA0;	// 0x51 종료
//	public static final int C_BOARD_READ = 0xA2;	// 게시판 읽기
//	public static final int C_MERCENARYEMPLOY = 0xA4;	// 용병구매
//	public static final int C_EMBLEM = 0xA7;	// 가시범위의 혈맹 마크 요청[폴더내 emblem삭제]
//	public static final int C_ALT_ATTACK = 0xA8;	// 찾음[본섭]  (현재 미사용 by feel)
//	public static final int C_ENTER_SHIP = 0xAB;	// 찾음[본섭]  (현재 미사용 by feel)
//	public static final int C_INVITE_PARTY = 0xAC;	// 찾음[본섭]  (현재 미사용 by feel)
//	public static final int C_REMOVE_BUDDY = 0xAD;	// 친구삭제
//	public static final int C_EXCHANGE_SPELL = 0xAE;	// 호런 마법목록에서 OK누르기
//	public static final int C_BANISH_PARTY = 0xAF;	// 파티 추방
//	public static final int C_LOGOUT = 0xB0;	// 다시 로긴창으로 넘어갈때
//	public static final int C_SHIFT_SERVER = 0xB3;	// 찾음[본섭] (사용안함_by feel )
//	public static final int C_BOOK = 0xB7;	// 찾음[본섭]  (현재 미사용 by feel)
//	public static final int C_INVITE_PARTY_TARGET = 0xB9;	// 파티 초대
//	public static final int C_BOARD_DELETE = 0xBE;	// 게시판 게시글 삭제
//	public static final int C_EXIT_GHOST = 0xC0;	// 무한대전 관람모드 탈출  (현재 미사용 by feel)
//	public static final int C_MATCH_MAKING = 0xC5;	// 찾음[본섭]  (현재 미사용 by feel)
//	public static final int C_CHECK_INVENTORY = 0xC6;	// 펫 인벤토리[펫 메뉴]
//	public static final int C_ENTER_PORTAL = 0xC7;	// (ENTER_PORTAL)
//	public static final int C_THROW = 0xC8;	// 낚시 종료
//	public static final int C_SILENCE = 0xC9;	// 찾음[본섭] (현재 미사용 by feel)
//	public static final int C_GOTO_PORTAL = 0xCB;	// 오른쪽 버튼으로 포탈 진입 확실치 않음
//	public static final int C_WAR = 0xCE;	// 전쟁
//	public static final int C_BOARD_WRITE = 0xCF;	// 게시판 쓰기
//	public static final int C_VOICE_CHAT = 0xD0;	// 스텟 초기화.
//	public static final int C_JOIN_PLEDGE = 0xD1;	// [가입]
//	public static final int C_TAX = 0xD4;	// 세금 조정
//	public static final int C_SMS = 0xD6;	// 문자    찾음[본섭]  (현재 미사용 by feel)
//	public static final int C_BUY_SELL = 0xD7;	// 상점 결과 처리
//	public static final int C_ONOFF = 0xD8;	// [환경설정->전챗켬,끔].
//	public static final int C_DEPOSIT = 0xD9;	// 성 공금 입금
//	public static final int C_REQUEST_ROLL = 0xDA;	// 찾음[본섭]  (현재 미사용 by feel)
//	public static final int C_START_CASTING = 0xDC;	// 찾음[본섭]  (현재 미사용 by feel)
//	public static final int C_BOARD_LIST = 0xDD;	// 게시판 next
//	public static final int C_MAIL = 0xDF;	// 편지 읽기
//	public static final int C_PLEDGE_WATCH = 0xE2;	// 문장 주시 혈맹 목록
//	public static final int C_RESTART = 0xE4;	// 겜중에 리스창으로 빠짐. [ C_CHARACTERCONFIG 다음에 날라옴 ]
//	public static final int C_SUMMON = 0xE5;	// CALL버튼 .감시
//	public static final int C_CHAT_PARTY_CONTROL = 0xE7;	// 채팅파티채팅초대
//	public static final int C_CLIENT_READY = 0xE8;	// 찾음[본섭]  (현재 미사용 by feel)
//	public static final int C_LOGIN = 0xE9;	// v 계정정보가 담긴 패킷
//	public static final int C_ENTER_WORLD = 0xEC;	// 리스창에서 케릭 선택
//	public static final int C_ATTACK_CONTINUE = 0xED;	// 자동칼질
//	public static final int C_CREATE_PLEDGE = 0xF4;	// 혈맹 창설
//	public static final int C_BAN_MEMBER = 0xF5;	// 혈맹 추방 명령어
//	public static final int C_ACTION = 0xF6;	// <알트+1 ~ 5 까지 액션 >
//	public static final int C_CHANGE_CASTLE_SECURITY = 0xF7;	// 성내 치안 관리
//	public static final int C_ANSWER = 0xF8;	// [ Y , N ] 선택 부분
//	public static final int C_DESTROY_ITEM = 0xFA;	// 휴지통에 아이템 삭제
//	public static final int C_SAVE = 0xFB;	// 무기수리 완료 - 예측  (현재 미사용 by feel)
//	public static final int C_DIALOG = 0xFC;	// Npc와 대화부분
//	public static final int C_BUY_SPELL = 0xFD;	// 스킬 구입 OK
//
//
//	public static final int S_CHANGE_PASSWORD_CHECK = 0x00;	// 찾음[본섭]  (현재 미사용 by feel)
//	public static final int S_WEATHER = 0x01;	// 날씨 조작하기
//	public static final int S_DRUNKEN = 0x02;	// 술
//	public static final int S_POISON = 0x04;	// 독과 굳은 상태 : 표현 비취나 큐어포이즌 써보면 됨
//	public static final int S_XCHG_RESULT = 0x05;	// 거래 취소, 완료
//	public static final int S_NOT_ENOUGH_FOR_SPELL = 0x0C;	// 호런 재료 부족
//	public static final int S_CHANGE_ATTR = 0x0D;	// 위치값을 이동가능&불가능 조작 부분
//	public static final int S_TELL = 0x0F;	// 귓속말
//	public static final int S_REQUEST_SUMMON = 0x11;	// 텔레포트[손바닥]
//	public static final int S_BOARD_READ = 0x12;	// 게시판 읽기
//	public static final int S_ROLL_RESULT = 0x14;	// 찾음[본섭]  (현재 미사용 by feel)
//	public static final int S_REMOVE_INVENTORY = 0x15;	// 인벤토리 아이템 삭제
//	public static final int S_CHANGE_DIRECTION = 0x16;	// 방향 전환 부분 [움직이는 엔피씨에 말걸어서 체크]
//	public static final int S_ADD_SPELL = 0x19;	// 스킬 추가[버프패킷박스 다음]
//	public static final int S_MERCENARYNAME = 0x1A;	// 찾음[본섭]  (현재 미사용 by feel)
//	public static final int S_CHANGE_ALIGNMENT = 0x1D;	// 라우풀
//	public static final int S_HIT_POINT = 0x20;	// HP 업데이트
//	public static final int S_NOTICE = 0x21;	// 로그인후 패킷
//	public static final int S_CLONE = 0x22;	// npc 변신(도펠갱어 등등) (현재 미사용 by feel)
//	public static final int S_DELETE_CHARACTER_CHECK = 0x23;	// 케릭 삭제
//	public static final int S_EFFECT = 0x25;	// 이팩트 부분 (헤이스트등)
//	public static final int S_PERSONAL_SHOP_LIST = 0x26;	// 개인상점 물품 열람
//	public static final int S_BLIND = 0x2A;	// 눈멀기 효과
//	public static final int S_CREATE_CHARACTER_CHECK = 0x2D;	// 캐릭터 생성시 처리부분
//	public static final int S_CHANGE_DESC = 0x2E;	// 오브젝트 네임변경시
//	public static final int S_BUYABLE_SPELL_LIST = 0x30;	// 스킬 구입 창
//	public static final int S_CHANGE_ITEM_USE = 0x31;	// 찾음[본섭]  (현재 미사용 by feel)
//	public static final int S_ATTACK_ALL = 0x32;	// 찾음[본섭]  (현재 미사용 by feel)
//	public static final int S_EXP = 0x34;	// 경험치 갱신  (현재 미사용 by feel)
//	public static final int S_MOVE_OBJECT = 0x36;	// 이동 오브젝트
//	public static final int S_TAX = 0x3A;	// 세율 조정
//	public static final int S_VOICE_CHAT = 0x3B;	// v 스텟 초기화 길이
//	public static final int S_COMMAND_TARGET = 0x3D;	// 찾음[본섭]  (현재 미사용 by feel)
//	public static final int S_ADD_INVENTORY_BATCH = 0x41;	// 인벤토리의 아이템리스트
//	public static final int S_AGIT_MAP = 0x42;	// 찾음[본섭]
//	public static final int S_SERVER_LIST = 0x44;	// 찾음[본섭]  (현재 미사용 by feel)
//	public static final int S_AC = 0x45;	// AC 및 속성방어 갱신 [블레스트 아머 사용시 나옴]
//	public static final int S_NEW_CHAR_INFO = 0x47;	// 케릭 새로 만든거 보내기
//	public static final int S_ACTION = 0x48;	// 액션 부분(맞는모습등)
//	public static final int S_CHARACTER_INFO = 0x4B;	// v 케릭터리스트의 케릭정보
//	public static final int S_MAGE_STRENGTH = 0x4D;	// 힘업
//	public static final int S_WITHDRAW = 0x4E;	// 공금 출금
//	public static final int S_PING = 0x4F;	// 찾음[본섭]  (현재 미사용 by feel)
//	public static final int S_MASTER = 0x51;	// 찾음[본섭]  (현재 미사용 by feel)
//	public static final int S_CRIMINAL = 0x52;	// 보라돌이
//	public static final int S_HYPERTEXT = 0x53;	// Npc클릭 Html열람
//	public static final int S_CHANGE_LEVEL = 0x55;	// 찾음[본섭]  (현재 미사용 by feel)
//	public static final int S_ASK = 0x57;	// [ Y , N ] 메세지
//	public static final int S_CASTLE_OWNER = 0x59;	// 성소유목록 세팅
//	public static final int S_RESTART = 0x5D;	// 찾음[본섭]
//	public static final int S_BLINK = 0x5E;	// 찾음[본섭]  (현재 미사용 by feel)
//	public static final int S_SELECTABLE_TIME_LIST = 0x5F;	// 공성시간 지정
//	public static final int S_VERSION_CHECK = 0x61;	// 서버버전  (현재 미사용 by feel)
//	public static final int S_WAR = 0x63;	// 전쟁
//	public static final int S_AGIT_LIST = 0x64;	// 아지트 리스트
//	public static final int S_CHANGE_LIGHT = 0x65;	// 밝기
//	public static final int S_SHOW_MAP = 0x67;	// 찾음[본섭]  (현재 미사용 by feel)
//	public static final int S_RESURRECT = 0x6D;	// 부활 처리 부분
//	public static final int S_PORTAL = 0x6E;	//
//	public static final int S_ATTACK_MANY = 0x70;	// 파톰 어퀘등의 스킬
//	public static final int S_REMOVE_SPELL = 0x78;	// 스킬 삭제 (정령력 제거) 힘투벗기
//	public static final int S_EVENT = 0x79;	// v 통합 패킷 관리 담당
//	public static final int S_ADD_BOOKMARK = 0x7B;	// 기억 리스트
//	public static final int S_ABILITY_SCORES = 0x7C;	// 스테이터스 갱신(디크리즈,민투)
//	public static final int S_IDENTIFY_CODE = 0x7D;	// 확인주문서
//	public static final int S_HIT_RATIO = 0x7E;	// 미니 HP표현 부분
//	public static final int S_CHANGE_ITEM_DESC_EX = 0x80;	// 인벤 아이템 갱신
//	public static final int S_NUM_CHARACTER = 0x82;	// v 해당 계정의 케릭 갯수
//	public static final int S_CHANGE_ITEM_DESC = 0x86;	// 아이템 착용 (E표시)
//	public static final int S_INVISIBLE = 0x87;	// 투명
//	public static final int S_SAY_CODE = 0x88;	// 샤우팅 글
//	public static final int S_MESSAGE = 0x8A;	// 시스템 메세지 (장사 채팅).
//	public static final int S_PLEDGE_WATCH = 0x8B;	// 혈맹 문장 주시
//	public static final int S_SELL_LIST = 0x8D;	// 상점에 판매 부분
//	public static final int S_FIXABLE_ITEM_LIST = 0x8E;	// 무기수리 리스트
//	public static final int S_MAGE_SHIELD = 0x90;	// 쉴드
//	public static final int S_READ_MAIL = 0x95;	// 찾음[본섭]  (현재 미사용 by feel)
//	public static final int S_BOARD_LIST = 0x97;	// 게시판 클릭
//	public static final int S_SLAVE_CONTROL = 0x99;	// 펫 공격 목표지정
//	public static final int S_EMBLEM = 0x9A;	// 클라에 혈문장 요청
//	public static final int S_ADD_XCHG = 0x9B;	// 거래창 아이템 추가 부분
//	public static final int S_SAY = 0x9C;	// 일반 채팅
//	public static final int S_STATUS = 0xA0;	// 케릭 정보 갱신
//	public static final int S_MAGE_DEXTERITY = 0xA1;	// 덱스업
//	public static final int S_TITLE = 0xA2;	// 호칭 변경
//	public static final int S_WARNING_CODE = 0xA3;	// 찾음[본섭]  (현재 미사용 by feel)
//	public static final int S_CHANGE_ITEM_TYPE = 0xA4;	// 찾음[본섭]  (현재 미사용 by feel)
//	public static final int S_BOOK_LIST = 0xA5;	// 찾음[본섭]  (현재 미사용 by feel)
//	public static final int S_MERCENARYARRANGE = 0xA9;	// 선택한 용병 주기
//	public static final int S_ATTACK = 0xAB;	// 공격 표현 부분
//	public static final int S_CLIENT_READY = 0xB2;	// 찾음[본섭]  (현재 미사용 by feel)
//	public static final int S_PUT_OBJECT = 0xB3;	// 오브젝트 그리기
//	public static final int S_EXTENDED_PROTOBUF = 0xB4;	// 종합 패킷
//	public static final int S_EXTENDED_HYBRID = 0xB5;	// 찾음[본섭]  (현재 미사용 by feel)
//	public static final int S_RETRIEVE_LIST = 0xB6;	// 창고 리스트
//	public static final int S_HYPERTEXT_INPUT = 0xB8;	// 수량성 아이템 제작 갯수 [여관]
//	public static final int S_WIELD = 0xBB;	// 무기 착,탈 부분
//	public static final int S_POLYMORPH = 0xBC;	// 변신
//	public static final int S_MANA_POINT = 0xBD;	// MP 업데이트
//	public static final int S_WORLD = 0xBE;	// 찾음[본섭]
//	public static final int S_SOUND_EFFECT = 0xC2;	// 사운드 이팩트 부분[펫 호루라기로 찾기]
//	public static final int S_MAIL_INFO = 0xC3;	// 편지 읽기.
//	public static final int S_EXCHANGEABLE_SPELL_LIST = 0xC6;	// 호런 마법 배우기창
//	public static final int S_ENTER_WORLD_CHECK = 0xC8;	// 접속담당
//	public static final int S_XCHG_START = 0xC9;	// 거래창 부분
//	public static final int S_TIME = 0xCA;	// 게임 시간
//	public static final int S_MATCH_MAKING = 0xCC;	// 찾음[본섭]  (현재 미사용 by feel)
//	public static final int S_MERCENARYSELECT = 0xCE;	// 고용한 용병을 배치
//	public static final int S_LOGIN_CHECK = 0xCF;	// 포탈이동시 날라오는 패킷(호런동굴들어갈때)확실치않음
//	public static final int S_PLEDGE = 0xD0;	// 클랜 업데이트, 아무 혈맹이나 가입하기
//	public static final int S_WANTED_LOGIN = 0xD1;	// 피케이 횟수 메시지
//	public static final int S_KICK = 0xD2;	// 해당 케릭 강제 종료
//	public static final int S_BUY_LIST = 0xD4;	// 상점 구입 부분[BUY]
//	public static final int S_EFFECT_LOC = 0xD5;	// 트랩 (좌표위 이펙트)  포우 슬레이어로 따면 됨
//	public static final int S_ARCHERARRANGE = 0xD7;	// 찾음[본섭]  (현재 미사용 by feel)
//	public static final int S_DEPOSIT = 0xD8;	// 공금 입금
//	public static final int S_EXTENDED = 0xDB;	// 아덴상점생존의 외침 등등
//	public static final int S_CHANGE_ACCOUNTINFO_CHECK = 0xDD;	// 찾음[본섭]  (현재 미사용 by feel)
//	public static final int S_CHANGE_COUNT = 0xDE;	// 찾음[본섭]  (현재 미사용 by feel)
//	public static final int S_CHANGE_ABILITY = 0xE0;	// 이반, 소반 인프라 사용
//	public static final int S_DECREE = 0xE1;	// 찾음[본섭]  (현재 미사용 by feel)
//	public static final int S_MAGIC_STATUS = 0xE5;	// sp와 mr변경
//	public static final int S_CHANGE_ITEM_BLESS = 0xE7;	// 봉인 주문서, 봉인줌서 사서 상아탑무기에 바르기
//	public static final int S_NEWS = 0xE9;	// 공지
//	public static final int S_KEY = 0xEB;	// 방향 전환 부분 [움직이는 엔피씨에 말걸어서 체크]  (현재 미사용 by feel)
//	public static final int S_EMOTION = 0xED;	// 용기
//	public static final int S_MERCENARYEMPLOY = 0xF0;	// 성 용병 고용  0612 - 안바낌
//	public static final int S_ADD_INVENTORY = 0xF5;	// 아이템 생성[아이템 떨궜다가먹기]
//	public static final int S_PARALYSE = 0xF9;	// 행동 제한 (커스패럴 상태) 사막 스콜피온한테 가서 커스당하기
//	public static final int S_REMOVE_OBJECT = 0xFA;	// 오브젝트 삭제 (토글etc)
//	public static final int S_NEW_ACCOUNT_CHECK = 0xFB;	// 찾음[본섭]  (현재 미사용 by feel)
//	public static final int S_SPEED = 0xFC;	// 헤이스트
//	public static final int S_MESSAGE_CODE = 0xFE;	// 서버 메세지[방어구중복으로체크]
//	public static final int S_BREATH = 0xFF;	// 에바 아이콘


	/**jpopcde 2021-02-05*/
	public static final int C_SERVER_SELECT = 0x03;// 3
	public static final int C_FAR_ATTACK = 0x04;// 4
	public static final int C_ASK_XCHG = 0x05;// 5
	public static final int C_BOARD_LIST = 0x06;// 6
	public static final int C_EXCLUDE = 0x07;// 7
	public static final int C_CHECK_PK = 0x09;// 9
	public static final int C_RANK_CONTROL = 0x0A;// 10
	public static final int C_MERCENARYSELECT = 0x0E;// 14
	public static final int C_SAY = 0x10;// 16
	public static final int C_LOGIN_RESULT = 0x12;// 18
	public static final int C_CHANGE_PASSWORD = 0x13;// 19
	public static final int C_UPLOAD_EMBLEM = 0x14;// 20
	public static final int C_MARRIAGE = 0x15;// 21
	public static final int C_GET = 0x17;// 23
	public static final int C_BUYABLE_SPELL = 0x18;// 24
	public static final int C_CREATE_PLEDGE = 0x1A;// 26
	public static final int C_READ_NOTICE = 0x1B;// 27
	public static final int C_EMBLEM = 0x1C;// 28
	public static final int C_SHIFT_SERVER = 0x1D;// 29
	public static final int C_TELEPORT_USER = 0x1F;// 31
	public static final int C_ANSWER = 0x21;// 33
	public static final int C_CREATE_CUSTOM_CHARACTER = 0x23;// 35
	public static final int C_DEPOSIT = 0x24;// 36
	public static final int C_NPC_ITEM_CONTROL = 0x25;// 37
	public static final int C_TAX = 0x29;// 41
	public static final int C_INVITE_PARTY_TARGET = 0x2A;// 42
	public static final int C_ATTACK = 0x2B;// 43
	public static final int C_SLAVE_CONTROL = 0x2D;// 45
	public static final int C_BAN = 0x2E;// 46
	public static final int C_ACTION = 0x32;// 50
	public static final int C_DIALOG = 0x33;// 51
	public static final int C_NEW_ACCOUNT = 0x34;// 52
	public static final int C_EXTENDED = 0x35;// 53
	public static final int C_CHANNEL = 0x37;// 55
	public static final int C_QUERY_BUDDY = 0x38;// 56
	public static final int C_DEAD_RESTART = 0x3A;// 58
	public static final int C_WITHDRAW = 0x3B;// 59
	public static final int C_GOTO_MAP = 0x3C;// 60
	public static final int C_CHANGE_CASTLE_SECURITY = 0x3F;// 63
	public static final int C_ADDR = 0x40;// 64
	public static final int C_BANISH_PARTY = 0x41;// 65
	public static final int C_TELL = 0x43;// 67
	public static final int C_QUIT = 0x44;// 68
	public static final int C_WAREHOUSE_CONTROL = 0x47;// 71
	public static final int C_LOGIN_TEST = 0x48;// 72
	public static final int C_CHANGE_DIRECTION = 0x4F;// 79
	public static final int C_DELETE_CHARACTER = 0x51;// 81
	public static final int C_INVITE_PARTY = 0x52;// 82
	public static final int C_BOOKMARK = 0x54;// 84
	public static final int C_LOGIN = 0x55;// 85
	public static final int C_QUERY_PERSONAL_SHOP = 0x56;// 86
	public static final int C_BUY_SELL = 0x59;// 89
	public static final int C_BOARD_WRITE = 0x5B;// 91
	public static final int C_BOARD_READ = 0x5D;// 93
	public static final int C_MAIL = 0x5F;// 95
	public static final int C_ALT_ATTACK = 0x60;// 96
	public static final int C_DROP = 0x61;// 97
	public static final int C_PERSONAL_SHOP = 0x62;// 98
	public static final int C_REGISTER_QUIZ = 0x64;// 100
	public static final int C_ENTER_PORTAL = 0x65;// 101
	public static final int C_CHANGE_ACCOUNTINFO = 0x68;// 104
	public static final int C_BAN_MEMBER = 0x69;// 105
	public static final int C_DELETE_BOOKMARK = 0x6A;// 106
	public static final int C_WHO_PARTY = 0x6C;// 108
	public static final int C_SELECT_TIME = 0x6D;// 109
	public static final int C_READ_NEWS = 0x6E;// 110
	public static final int C_ACCEPT_XCHG = 0x6F;// 111
	public static final int C_LEAVE_PLEDGE = 0x70;// 112
	public static final int C_DUEL = 0x76;// 118
	public static final int C_LEAVE_PARTY = 0x77;// 119
	public static final int C_CHAT_PARTY_CONTROL = 0x78;// 120
	public static final int C_PLATE = 0x79;// 121
	public static final int C_VERSION = 0x7A;// 122
	public static final int C_BUY_SPELL = 0x7B;// 123
	public static final int C_REMOVE_BUDDY = 0x7C;// 124
	public static final int C_EXCHANGEABLE_SPELL = 0x7D;// 125
	public static final int C_BOOK = 0x7E;// 126
	public static final int C_SAVEIO = 0x80;// 128
	public static final int C_ATTACK_CONTINUE = 0x82;// 130
	public static final int C_OPEN = 0x83;// 131
	public static final int C_CONTROL_WEATHER = 0x84;// 132
	public static final int C_WHO_PLEDGE = 0x87;// 135
	public static final int C_GIVE = 0x89;// 137
	public static final int C_ADD_BUDDY = 0x8A;// 138
	public static final int C_BLINK = 0x8B;// 139
	public static final int C_SHUTDOWN = 0x8C;// 140
	public static final int C_JOIN_PLEDGE = 0x8D;// 141
	public static final int C_START_CASTING = 0x90;// 144
	public static final int C_THROW = 0x92;// 146
	public static final int C_RETURN_SUMMON = 0x93;// 147
	public static final int C_MERCENARYNAME = 0x94;// 148
	public static final int C_SAVE = 0x96;// 150
	public static final int C_EXTENDED_PROTOBUF = 0x9D;// 157
	public static final int C_CHECK_INVENTORY = 0xA0;// 160
	public static final int C_BUILDER_CONTROL = 0xA1;// 161
	public static final int C_SUMMON = 0xA4;// 164
	public static final int C_SELECTABLE_TIME = 0xA7;// 167
	public static final int C_ENTER_WORLD = 0xA8;// 168
	public static final int C_MERCENARYARRANGE = 0xA9;// 169
	public static final int C_CHAT = 0xAA;// 170
	public static final int C_QUERY_CASTLE_SECURITY = 0xAB;// 171
	public static final int C_WHO = 0xAE;// 174
	public static final int C_MOVE = 0xAF;// 175
	public static final int C_ALIVE = 0xB0;// 176
	public static final int C_MONITOR_CONTROL = 0xB2;// 178
	public static final int C_EXIT_GHOST = 0xB3;// 179
	public static final int C_ONOFF = 0xB8;// 184
	public static final int C_ENTER_SHIP = 0xB9;// 185
	public static final int C_HYPERTEXT_INPUT_RESULT = 0xBC;// 188
	public static final int C_ARCHERARRANGE = 0xBE;// 190
	public static final int C_RESTART = 0xC2;// 194
	public static final int C_CANCEL_XCHG = 0xC3;// 195
	public static final int C_WAR = 0xC5;// 197
	public static final int C_DESTROY_ITEM = 0xC6;// 198
	public static final int C_GOTO_PORTAL = 0xC8;// 200
	public static final int C_PLEDGE_WATCH = 0xC9;// 201
	public static final int C_CLIENT_READY = 0xCA;// 202
	public static final int C_EXTENDED_HYBRID = 0xCF;// 207
	public static final int C_USE_ITEM = 0xD0;// 208
	public static final int C_EXCHANGE_SPELL = 0xD2;// 210
	public static final int C_TITLE = 0xD6;// 214
	public static final int C_USE_SPELL = 0xD8;// 216
	public static final int C_INCLUDE = 0xD9;// 217
	public static final int C_MATCH_MAKING = 0xDD;// 221
	public static final int C_BOARD_DELETE = 0xDE;// 222
	public static final int C_SILENCE = 0xDF;// 223
	public static final int C_SMS = 0xE0;// 224
	public static final int C_TELEPORT = 0xE2;// 226
	public static final int C_HACTION = 0xE3;// 227
	public static final int C_FIX = 0xE4;// 228
	public static final int C_WANTED = 0xE7;// 231
	public static final int C_VOICE_CHAT = 0xE8;// 232
	public static final int C_FIXABLE_ITEM = 0xE9;// 233
	public static final int C_LOGOUT = 0xEB;// 235
	public static final int C_REQUEST_ROLL = 0xEC;// 236
	public static final int C_ADD_XCHG = 0xF7;// 247
	public static final int C_KICK = 0xFC;// 252
	public static final int C_MERCENARYEMPLOY = 0xFD;// 253
	public static final int C_WISH = 0xFE;// 254


	public static final int S_AGIT_LIST = 0x00;// 0
	public static final int S_MASTER = 0x01;// 1
	public static final int S_ADD_BOOKMARK = 0x02;// 2
	public static final int S_MAGE_STRENGTH = 0x04;// 4
	public static final int S_ATTACK = 0x05;// 5
	public static final int S_ROLL_RESULT = 0x06;// 6
	public static final int S_CHANGE_ITEM_TYPE = 0x08;// 8
	public static final int S_WITHDRAW = 0x0C;// 12
	public static final int S_MERCENARYARRANGE = 0x0D;// 13
	public static final int S_DECREE = 0x0E;// 14
	public static final int S_CHANGE_COUNT = 0x0F;// 15
	public static final int S_POLYMORPH = 0x10;// 16
	public static final int S_BREATH = 0x11;// 17
	public static final int S_AGIT_MAP = 0x12;// 18
	public static final int S_EXTENDED_PROTOBUF = 0x13;// 19
	public static final int S_ADD_SPELL = 0x15;// 21
	public static final int S_SLAVE_CONTROL = 0x16;// 22
	public static final int S_CRIMINAL = 0x18;// 24
	public static final int S_MAGIC_STATUS = 0x19;// 25
	public static final int S_PERSONAL_SHOP_LIST = 0x1D;// 29
	public static final int S_ADD_INVENTORY = 0x1E;// 30
	public static final int S_CHARACTER_INFO = 0x1F;// 31
	public static final int S_PARALYSE = 0x21;// 33
	public static final int S_TITLE = 0x24;// 36
	public static final int S_CHANGE_ATTR = 0x26;// 38
	public static final int S_EXTENDED_HYBRID = 0x27;// 39
	public static final int S_SELL_LIST = 0x28;// 40
	public static final int S_EXP = 0x29;// 41
	public static final int S_CHANGE_PASSWORD_CHECK = 0x2A;// 42
	public static final int S_VOICE_CHAT = 0x2B;// 43
	public static final int S_BUYABLE_SPELL_LIST = 0x2C;// 44
	public static final int S_WARNING_CODE = 0x2D;// 45
	public static final int S_SERVER_LIST = 0x2E;// 46
	public static final int S_HIT_POINT = 0x2F;// 47
	public static final int S_DEPOSIT = 0x31;// 49
	public static final int S_REMOVE_OBJECT = 0x33;// 51
	public static final int S_REQUEST_SUMMON = 0x34;// 52
	public static final int S_MERCENARYNAME = 0x39;// 57
	public static final int S_CHANGE_LEVEL = 0x3C;// 60
	public static final int S_SAY_CODE = 0x3D;// 61
	public static final int S_WAR = 0x3F;// 63
	public static final int S_MERCENARYEMPLOY = 0x42;// 66
	public static final int S_CHANGE_ACCOUNTINFO_CHECK = 0x43;// 67
	public static final int S_MAGE_SHIELD = 0x45;// 69
	public static final int S_CHANGE_ITEM_BLESS = 0x46;// 70
	public static final int S_CHANGE_DESC = 0x47;// 71
	public static final int S_PLEDGE_WATCH = 0x4E;// 78
	public static final int S_LOGIN_CHECK = 0x51;// 81
	public static final int S_REMOVE_SPELL = 0x52;// 82
	public static final int S_NEW_ACCOUNT_CHECK = 0x53;// 83
	public static final int S_CHANGE_ALIGNMENT = 0x54;// 84
	public static final int S_ASK = 0x55;// 85
	public static final int S_EFFECT = 0x56;// 86
	public static final int S_XCHG_START = 0x58;// 88
	public static final int S_RESTART = 0x59;// 89
	public static final int S_SOUND_EFFECT = 0x5B;// 91
	public static final int S_EMOTION = 0x5C;// 92
	public static final int S_SPEED = 0x5D;// 93
	public static final int S_TAX = 0x5F;// 95
	public static final int S_REMOVE_INVENTORY = 0x62;// 98
	public static final int S_MAIL_INFO = 0x63;// 99
	public static final int S_MESSAGE_CODE = 0x66;// 102
	public static final int S_TELL = 0x68;// 104
	public static final int S_AC = 0x6A;// 106
	public static final int S_VERSION_CHECK = 0x6B;// 107
	public static final int S_EVENT = 0x6C;// 108
	public static final int S_EXTENDED = 0x6D;// 109
	public static final int S_PLEDGE = 0x6E;// 110
	public static final int S_SAY = 0x70;// 112
	public static final int S_BLIND = 0x72;// 114
	public static final int S_STATUS = 0x74;// 116
	public static final int S_ENTER_WORLD_CHECK = 0x75;// 117
	public static final int S_CHANGE_DIRECTION = 0x78;// 120
	public static final int S_CHANGE_ABILITY = 0x7A;// 122
	public static final int S_RETRIEVE_LIST = 0x7F;// 127
	public static final int S_CLIENT_READY = 0x80;// 128
	public static final int S_NOT_ENOUGH_FOR_SPELL = 0x81;// 129
	public static final int S_BUY_LIST = 0x83;// 131
	public static final int S_SHOW_MAP = 0x84;// 132
	public static final int S_MATCH_MAKING = 0x85;// 133
	public static final int S_FIXABLE_ITEM_LIST = 0x88;// 136
	public static final int S_ATTACK_MANY = 0x89;// 137
	public static final int S_WORLD = 0x8D;// 141
	public static final int S_DELETE_CHARACTER_CHECK = 0x8F;// 143
	public static final int S_HYPERTEXT = 0x90;// 144
	public static final int S_ADD_XCHG = 0x91;// 145
	public static final int S_BOARD_LIST = 0x98;// 152
	public static final int S_MESSAGE = 0x99;// 153
	public static final int S_READ_MAIL = 0x9B;// 155
	public static final int S_TIME = 0x9C;// 156
	public static final int S_MERCENARYSELECT = 0x9E;// 158
	public static final int S_INVISIBLE = 0xA0;// 160
	public static final int S_EMBLEM = 0xA1;// 161
	public static final int S_CHANGE_ITEM_DESC_EX = 0xA4;// 164
	public static final int S_SELECTABLE_TIME_LIST = 0xA6;// 166
	public static final int S_XCHG_RESULT = 0xA7;// 167
	public static final int S_CLONE = 0xAC;// 172
	public static final int S_EXCHANGEABLE_SPELL_LIST = 0xAF;// 175
	public static final int S_WEATHER = 0xB0;// 176
	public static final int S_NEWS = 0xB3;// 179
	public static final int S_IDENTIFY_CODE = 0xB5;// 181
	public static final int S_PUT_OBJECT = 0xBA;// 186
	public static final int S_BLINK = 0xBD;// 189
	public static final int S_NUM_CHARACTER = 0xBE;// 190
	public static final int S_WIELD = 0xC1;// 193
	public static final int S_CHANGE_ITEM_DESC = 0xC2;// 194
	public static final int S_MAGE_DEXTERITY = 0xC4;// 196
	public static final int S_RESURRECT = 0xC5;// 197
	public static final int S_PING = 0xC6;// 198
	public static final int S_PORTAL = 0xCA;// 202
	public static final int S_NEW_CHAR_INFO = 0xCC;// 204
	public static final int S_CHANGE_LIGHT = 0xCE;// 206
	public static final int S_MOVE_OBJECT = 0xD3;// 211
	public static final int S_NOTICE = 0xD4;// 212
	public static final int S_POISON = 0xD5;// 213
	public static final int S_CREATE_CHARACTER_CHECK = 0xD7;// 215
	public static final int S_ADD_INVENTORY_BATCH = 0xD8;// 216
	public static final int S_EFFECT_LOC = 0xDB;// 219
	public static final int S_ABILITY_SCORES = 0xDF;// 223
	public static final int S_HYPERTEXT_INPUT = 0xE0;// 224
	public static final int S_WANTED_LOGIN = 0xE1;// 225
	public static final int S_ACTION = 0xE2;// 226
	public static final int S_COMMAND_TARGET = 0xE4;// 228
	public static final int S_DRUNKEN = 0xE5;// 229
	public static final int S_KEY = 0xE7;// 231
	public static final int S_CHANGE_ITEM_USE = 0xED;// 237
	public static final int S_BOOK_LIST = 0xEE;// 238
	public static final int S_ATTACK_ALL = 0xF0;// 240
	public static final int S_KICK = 0xF5;// 245
	public static final int S_BOARD_READ = 0xF8;// 248
	public static final int S_ARCHERARRANGE = 0xF9;// 249
	public static final int S_HIT_RATIO = 0xFA;// 250
	public static final int S_CASTLE_OWNER = 0xFC;// 252
	public static final int S_MANA_POINT = 0xFE;// 254
	/**jpopcde 2021-02-05*/

	public static final byte[] S_KEYBYTES = {
			(byte) (S_KEY & 0xff),

			(byte) 0x4c, (byte) 0xbe, (byte) 0x75, (byte) 0x5d,
			(byte) 0x23, (byte) 0x75, (byte) 0x5a, (byte) 0x75,
	};

	public static long getSeed(){
		long seed = S_KEYBYTES[1] & 0xff;
		seed |= ((S_KEYBYTES[2] << 8) & 0xff00);
		seed |= ((S_KEYBYTES[3] << 16) & 0xff0000);
		seed |= ((S_KEYBYTES[4] << 24) & 0xff000000);

		return seed;
	}

	public static final byte[] VERSIONBYTES_HEAD = {
			(byte) 0x38, //set_status_start_time
			//bb 9b e8 ef 05
			(byte) 0xbb, (byte) 0x9b, (byte) 0xe8, (byte) 0xef, (byte) 0x05,
			(byte) 0x40, // set_english_only_config
			(byte) 0x00,
			(byte) 0x48, // set_country_code
			(byte) 0x00,
			(byte) 0x50, // set_client_setting_switch
			//8b fb ff a7 03
			(byte) 0x8b, (byte) 0xfb, (byte) 0xff, (byte) 0xa7, (byte) 0x03,
			(byte) 0x58, // set_game_real_time
	};

	public static final byte[] VERSIONBYTES_TAIL = {
			(byte) 0x60, // set_global_cache_version
			//fc 97 87 48
			(byte) 0xfc, (byte) 0x97, (byte) 0x87, (byte) 0x48,
			(byte) 0x68, // set_tam_server_version
			//ef f8 fc 8c 07
			(byte) 0xef, (byte) 0xf8, (byte) 0xfc, (byte) 0x8c, (byte) 0x07,
			(byte) 0x70, // set_arca_server_version
			//f0 f8 fc 8c 07 　　
			(byte) 0xf0, (byte) 0xf8, (byte) 0xfc, (byte) 0x8c, (byte) 0x07,
			(byte) 0x78, // set_hibreed_inter_server_version
			//b9 aa de 8f 07
			(byte) 0xb9, (byte) 0xaa, (byte) 0xde, (byte) 0x8f, (byte) 0x07,
			(byte) 0x80, (byte) 0x01, // set_arenaco_server_version
			//89 b1	e1 8f 07
			(byte) 0x89, (byte) 0xb1, (byte) 0xe1, (byte) 0x8f, (byte) 0x07,
			(byte) 0x88, (byte) 0x01, // set_server_type
			(byte) 0x00,
	};
}
